"""add whatsapp intake tables

Revision ID: c7a1e9f3b2d4
Revises: d412dcfb803a
Create Date: 2026-10-07 00:00:00.000000

Adds the WhatsApp intake tables (accounts / messages / attachments), mirroring
the email_* tables. Hand-written rather than autogenerated so it carries only
the real creates — autogenerate on this project also emits spurious drop_index
ops for indexes that exist but aren't declared index=True on the models.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a1e9f3b2d4'
down_revision: Union[str, Sequence[str], None] = 'd412dcfb803a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'whatsapp_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=False),
        sa.Column('label', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('connected_at', sa.String(), nullable=True),
        sa.Column('last_received_at', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('org_id'),
        sa.UniqueConstraint('phone_number'),
    )
    op.create_table(
        'whatsapp_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('whatsapp_account_id', sa.Integer(), nullable=False),
        sa.Column('provider_message_sid', sa.String(), nullable=False),
        sa.Column('sender_waid', sa.String(), nullable=True),
        sa.Column('sender_name', sa.String(), nullable=True),
        sa.Column('body', sa.String(), nullable=True),
        sa.Column('received_at', sa.String(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['whatsapp_account_id'], ['whatsapp_accounts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('whatsapp_account_id', 'provider_message_sid', name='uq_wa_message_per_account'),
    )
    op.create_table(
        'whatsapp_attachments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('whatsapp_message_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('mime_type', sa.String(), nullable=True),
        sa.Column('media_path', sa.String(), nullable=True),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('next_retry_at', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['whatsapp_message_id'], ['whatsapp_messages.id'], ),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    # Indexes for the org-scoped hot paths (match the email_* tables).
    op.create_index("ix_whatsapp_messages_org", "whatsapp_messages", ["org_id"])
    op.create_index("ix_whatsapp_attachments_org_status", "whatsapp_attachments", ["org_id", "status"])
    op.create_index("ix_whatsapp_attachments_message", "whatsapp_attachments", ["whatsapp_message_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_whatsapp_attachments_message", table_name="whatsapp_attachments")
    op.drop_index("ix_whatsapp_attachments_org_status", table_name="whatsapp_attachments")
    op.drop_index("ix_whatsapp_messages_org", table_name="whatsapp_messages")
    op.drop_table('whatsapp_attachments')
    op.drop_table('whatsapp_messages')
    op.drop_table('whatsapp_accounts')
